language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19


before_install:
  - yes | sdkmanager "platforms;android-29"
  - chmod 755 gradlew
  - ./gradlew dependencies || true

script:
  - ./gradlew assembleRelease --info
  - pwd
  - ls -lha build
  - ls -lha build/outputs
  - ls -lha build/outputs/apk
  - ls -lha build/outputs/apk/debug
